
GET http://localhost:3000

###Mails test
POST http://localhost:3000/mails/send
Content-Type: application/json

{ "email" : "templatico@mailer.com",
 "name": "Node APi", 
 "subject": "Test case",
"message": "ignition started"
   } 


### contacts
POST http://localhost:3000/contacts/add
Content-Type: application/json
 {
    "contact_name": "templatico",
    "contact_email": "templatico@mailer.com",
    "contact_phone": "+123456789"
  }



### contacts
GET http://localhost:3000/contacts
Content-Type: application/json

 {
    "contact_name": "templatico",
    "contact_email": "templatico@mailer.com",
    "contact_phone": "+123456789"
  }
