
GET http://localhost:3000

###Mails test
POST http://localhost:3000/mails/send
Content-Type: application/json

{ "email" : "templatico@mailer.com",
 "name": "Node APi", 
 "subject": "Test case",
"message": "ignition started"
   } 


### contacts
POST http://localhost:3000/contacts/add
Content-Type: application/json

{ "email" : "templatico@mailer.com",
 "name": "Node APi", 
 "email": "Test case",
   } 